### ISSUE TITLE
NPE from FacesServlet on page load

### ISSUE THREAD

**Issue by jesse-gallagher** [darwino/xpages-runtime#1]
This has to do with ServletContext#getNamedDispatcher, which may be stubbed out currently.

```
[err] java.lang.NullPointerException
[err] 	at com.ibm.xsp.webapp.FacesServlet.handleFileDownload(FacesServlet.java:977)
[err] 	at com.ibm.xsp.webapp.FacesServlet.service(FacesServlet.java:129)
[err] 	at com.ibm.xsp.webapp.FacesServletEx.service(FacesServletEx.java:138)
[err] 	at com.ibm.xsp.webapp.DesignerFacesServlet.service(DesignerFacesServlet.java:103)
[err] 	at com.darwino.xsp.ios.app.services.XPagesService.service(XPagesService.java:49)
[err] 	at com.darwino.commons.services.HttpServiceMatcher.service(HttpServiceMatcher.java:95)
[err] 	at com.darwino.commons.services.HttpServiceFactories._service(HttpServiceFactories.java:114)
[err] 	at com.darwino.commons.services.HttpServiceFactories.service(HttpServiceFactories.java:110)
[err] 	at com.darwino.j2ee.servlet.server.servlet.ServiceDispatcherFilter.service(ServiceDispatcherFilter.java:195)
[err] 	at com.darwino.j2ee.servlet.server.servlet.ServiceDispatcherFilter.doFilter(ServiceDispatcherFilter.java:162)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at com.darwino.j2ee.application.DarwinoJ2EEFilter.doFilter(DarwinoJ2EEFilter.java:221)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at com.darwino.j2ee.servlet.authentication.AuthenticationFilter.chainFilter(AuthenticationFilter.java:219)
[err] 	at com.darwino.j2ee.servlet.authentication.AuthenticationFilter.doFilter(AuthenticationFilter.java:211)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at com.darwino.j2ee.servlet.cors.CORSFilter.handleNonCORS(CORSFilter.java:453)
[err] 	at com.darwino.j2ee.servlet.cors.CORSFilter.doFilter(CORSFilter.java:189)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at com.darwino.j2ee.servlet.resources.GlobalPathRewriterFilter.doFilter(GlobalPathRewriterFilter.java:91)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at com.darwino.j2ee.servlet.gzip.GZipServletFilter.doFilter(GZipServletFilter.java:78)
[err] 	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:201)
[err] 	at [internal classes]
[err] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[err] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[err] 	at java.lang.Thread.run(Thread.java:748)

```

**Comment by jesse-gallagher** [comment]
The trouble is more that it's looking for "Designer Resource Servlet", which isn't loaded. We could either load it as a true servlet in the Jetty config or wrap around this.

**Comment by jesse-gallagher** [comment]
I haven't seen this in a bit, so it may have been fixed by another change.
